In [1]:
import pandas as pd

In [2]:
# Load data
df = pd.read_csv('new_york_data.csv', index_col = 0)

/var/folders/4n/51fny6wj15lbcvykgf0dns700000gn/T/ipykernel_824/2460435638.py:2: DtypeWarning: Columns (6,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('new_york_data.csv', index_col = 0)

In [3]:
df.shape

(30689921, 17)

In [4]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,date,avgTemp,value,bike_rides_daily
0,DF208007EE5F9D79,classic_bike,2022-08-26 15:21:44,2022-08-26 15:34:20,Berkeley Pl & 6 Ave,4134.06,Windsor Pl & 8 Ave,3620.02,40.676530,-73.978469,40.660906,-73.983074,member,2022-08-26,27.4,1,111955
1,4BF322F1E0D74152,classic_bike,2022-08-26 16:08:53,2022-08-26 16:17:48,W 44 St & 11 Ave,6756.05,8 Ave & W 33 St,6450.12,40.762009,-73.996975,40.751551,-73.993934,member,2022-08-26,27.4,1,111955
2,301E3D811B0D5219,classic_bike,2022-08-26 02:34:33,2022-08-26 08:29:41,9 Ave & W 45 St,6717.06,8 Ave & W 33 St,6450.12,40.760193,-73.991255,40.751551,-73.993934,member,2022-08-26,27.4,1,111955
3,7D4E20D0A43FCE1F,classic_bike,2022-08-26 11:25:26,2022-08-26 11:52:19,Central Ave & Covert St,4550.05,DeKalb Ave & Hudson Ave,4513.06,40.689290,-73.909510,40.689888,-73.981013,casual,2022-08-26,27.4,1,111955
4,BB560C341D35EB7D,electric_bike,2022-08-26 19:46:08,2022-08-26 19:48:11,21 St & 43 Ave,6395.01,9 St & 44 Rd,6361.03,40.750525,-73.945948,40.749660,-73.952100,member,2022-08-26,27.4,1,111955

In [5]:
# Take random sample of df
percentage = 0.001
subset_size = int(len(df) * percentage)

In [6]:
df_subset = df.sample(n = subset_size)

In [7]:
df_subset.shape

(30689, 17)

In [8]:
df_subset.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,date,avgTemp,value,bike_rides_daily
15010177,862862EBB854CB2D,classic_bike,2022-06-23 21:56:09,2022-06-23 22:05:22,Dean St & Hoyt St,4446.05,Court St & Nelson St,4077.07,40.686444,-73.987591,40.676395,-73.998699,casual,2022-06-23,19.2,1,120734
23277160,AB2EA8F6FEA6F206,classic_bike,2022-05-31 00:26:40,2022-05-31 01:01:26,Plaza Dr & W 170 St,8213.01,Audobon Ave & W 179 St,8316.02,40.840812,-73.917884,40.847305,-73.933291,member,2022-05-31,28.3,1,102957
24976804,A6BB2BA39124C938,classic_bike,2022-07-10 17:03:36,2022-07-10 17:30:49,Adelphi St & Myrtle Ave,4620.02,Brooklyn Bridge Park - Pier 2,4756.04,40.693083,-73.971789,40.698458,-73.997178,casual,2022-07-10,23.4,1,118774
25810912,76BF17F8B6AC4E86,classic_bike,2022-07-27 09:04:21,2022-07-27 09:13:57,E 20 St & 2 Ave,5971.08,1 Ave & E 16 St,5779.08,40.735877,-73.982050,40.732219,-73.981656,casual,2022-07-27,25.5,1,128834
3812228,387842FB6F927A39,classic_bike,2022-10-31 15:27:26,2022-10-31 15:52:23,Crescent St & 30 Ave,6958.06,31 St & Ditmars Blvd,7144.02,40.768692,-73.924957,40.776168,-73.910485,casual,2022-10-31,14.4,1,99493

In [9]:
# Export to csv
df_subset.to_csv('subset_new_york_data.csv')